import React from "react"

export const svePizze = [
    {
        id: 0,
        osoba:"",
        ime: "MARGARITA",
        opis: "Rajčica, mozzarella bocconcini, maslinovo ulje, bosiljak",
        cijena: 50,
    },
    {
        id: 1,
        osoba:"",
        ime: "MARGARITA DI BUFFALA",
        opis: "Rajčica, buffalo mozzarella, maslinovo ulje, bosiljak",
        cijena: 60,
    },
    {
        id: 2,
        osoba:"",
        ime: "FUNGHI",
        opis: "Rajčica, mozzarella bocconcini, šampinjoni, bukovače, shitake, rukola",
        cijena: 58,
    },
    {
        id: 3,
        osoba:"",
        ime: "CAPRICCIOSA",
        opis: "Rajčica, dimljena mozzarella, šunka, šampinjoni",
        cijena: 65,
    },
    {
        id: 4,
        osoba:"",
        ime: "FORMAGGIO",
        opis: "Rajčica, mozzarella bocconcini, buffala mozzarella, dimljena mozzarella, gorgonzola, grana padano, bosiljak",
        cijena: 65,
    },
    {
        id: 5,
        osoba:"",
        ime: "PICCANTE",
        opis: "Rajčica, mozzarella bocconcini, nduja, salami pikante, panceta, ukiseljeni jalapenosi, mini mozzarella",
        cijena: 68,
    },
    {
        id: 6,
        osoba:"",
        ime: "INĆUNI (ACCIUGHE)",
        opis: "Rajčica, mozzarella bocconcini, češnjak u maslinovom ulju, kapare, inćuni, plod kapara, rukola, kalamata masline, grana padano",
        cijena: 65,
    },
    {
        id: 7,
        osoba:"",
        ime: "VERDURE",
        opis: "Rajčica, mozzarella bocconcini, šampinjoni, tikvice, cherry rajčice, paprika, kapare, matovilac, kalamata masline, mini mozzarelle",
        cijena: 60,
    },
    {
        id: 8,
        osoba:"",
        ime: "PROSCIUTTO",
        opis: "Rajčica, mozzarella bocconcini, pršut, cherry rajčice, rukola, grana padano, kalamata masline",
        cijena: 68,
    },
    {
        id: 9,
        osoba:"",
        ime: "BRESAOLA",
        opis: "Rajčica, buffala mozzarella, sušena tanko rezana govedina, rukola, orasi, kalamata masline, mini mozzarella, maslinovo ulje",
        cijena: 75,
    },
    {
        id: 10,
        osoba:"",
        ime: "CARPACCIO TUNA",
        opis: "Rajčica, buffala mozzarella, češnjak u maslinovom ulju, kapare, rukola, dimljena, tuna, limun, plod kapara, mini mozzarele, kalamata masline",
        cijena: 85,
    },
    {
        id: 11,
        osoba:"",
        ime: "SALAMI",
        opis: "Rajčica, mozzarella bocconcini, salama od crne slavonske svinje, cherry rajčice, kalamata masline, mini mozzarelle, maslinovo ulje, bosiljak",
        cijena: 68,
    },
    {
        id: 12,
        osoba:"",
        ime: "FIOR DI ZUCCA",
        opis: "Pesto, cvijet tikvice, buffalo mozzarella, cherry rajčice, kalamata masline, bosiljak",
        cijena: 78,
    },
    {
        id: 13,
        osoba:"",
        ime: "JULIEN BIFTEK",
        opis: "Rajčica, mozzarella di buffala, julien biftek, rukola, grana padano, kalamata masline, mini mozzarella",
        cijena: 85,
    },
    {
        id: 14,
        osoba:"",
        ime: "PIZZA ROAST BEEF",
        opis: "Rajčica, mozzarella bocconcini, roast beef, baby špinat, cherry rajčica, mini mozzarella, krema aceto balsamico, krem sir, masline",
        cijena: 78,
    },
]